### ISSUE TITLE
Need contribution guide

### ISSUE THREAD

**Issue by kenya888** [Wunderfitz/harbour-piepmatz#10]
Hi, thank you for nice product:)
I wonder if you are now open for contribution(patch,suggestion,etc...)
When you become ready please write it to README.md :)

Thanks you again for your passion for SFOS:)

**Comment by Wunderfitz** [comment]
Hi, you can contribute at any time, no matter if it's code, translation, bug report or any suggestion. Instructions how to build Piepmatz locally are already available in the README. What are you missing?

However, just a small wish: In case you want to contribute larger amounts of code, please let me know upfront - just in case you are about to develop something which I'm already working on. Moreover, I would appreciate it if you more or less stick to the style I applied. Thanks!
