### ISSUE TITLE
v1.9 crash on Xperia 10 II

### ISSUE THREAD

**Issue by Karry** [Wunderfitz/harbour-piepmatz#109]
Hi. I have enabled coredumps on my phone, and just found out that piepmatz crashed few days ago. I have no idea what happened that time. Are you interested for coredump? I may share it privately. 

I tried to build v1.9 with debug info myself, but it seems that symbols doesn't match with distributed version :-( Probably different SDK was used. Or if you have debuginfo package (aarch64) available, it would be great to share it.

**Comment by Wunderfitz** [comment]
Well, if it's reproducible, any hint about a bug is appreciated. However, I have to admit that I have no experience in analyzing core dumps... Does it happen regularly?

**Comment by Karry** [comment]
Nope. It is not happening regularly unfortunately (luckily for standard users :-) ). It would be great to build and publish debug packages for next release. Just build app with `sfdk build --enable-debug`. GDB may be installed on the phone directly, with debug symbols, you can show backtrace in time of crash...

I am closing this issue meanwhile, if you don't have debug package for version 1.9.
