### ISSUE TITLE
Invalid or expired token

### ISSUE THREAD

**Issue by minodesign** [Wunderfitz/harbour-piepmatz#110]
I am installing Piepmatz on Xperia X but at the first opening of the app, instead of Twitter I see a white page and the it appear a "Invalid or expired token message"

Version is Salifish OS Verla
hallo

**Comment by Wunderfitz** [comment]
Just did a fresh install on a Verla without any configs on the device - login worked smoothly. Did you have an older install of Piepmatz on the device? Just in case: Remove ~/.config/harbour-piepmatz and restart the app.

**Comment by bferturk** [comment]
I am fresh install verla on redmi5 plus. I have same problem.
how to solve the problem : Copy sailfish browser desktop file in usr/share/applications to /home/defaultuser/
`cp -a sailfish-browser.desktop /home/defaultuser/.local/sh
are/applications/.
`
restart piepmatz
After you see two browser applications icon home screen. I'm login twitter this method

**Comment by nowave7** [comment]
No, copying that file does not help. It only gives you an option to choose with what you want to open your twitter links with, and an additional browser icon in the app menu. I'm still getting the before mentioned error message.

**Comment by Wunderfitz** [comment]
I finally made a new version 1.10 that should address the issues with the open-URL-with-browser issue should be fixed. Not sure if this is really related to this token error, but please give it a try and provide some feedback. Thanks!

**Comment by bferturk** [comment]
I fresh install  Verla . Problem solved 1.10 version . Many thanks @Wunderfitz

**Comment by Wunderfitz** [comment]
Wonderful, closing the issue then.
