### ISSUE TITLE
Saved Searches

### ISSUE THREAD

**Issue by maidis** [Wunderfitz/harbour-piepmatz#12]
It would be nice to have this functionality. This feature can make easier frequent search queries. This feature can basically have the following features:

- Save a Twitter search
- Remove a Twitter search
- Make a search by selecting a saved search

https://support.twitter.com/articles/96646
https://www.dropbox.com/s/6wh0oyqeteacyxm/sailfish-twitter-saved-searches.png?dl=0

**Comment by Wunderfitz** [comment]
Thanks for the request, putting that on my list. However, there are some more important things to implement before that... :)
