### ISSUE TITLE
Auth PIN

### ISSUE THREAD

**Issue by cfabric** [Wunderfitz/harbour-piepmatz#15]
Hello, 

I am assuming, piepmatz is supposed to open a website that generates a PIN from the Twitter API, but no browser window is opened, and I don't know where I would get the PIN otherwise.

Thanks
C

**Comment by Wunderfitz** [comment]
Hi C,

which device and which OS version are you using? Do you have any patches installed, especially any which interfere with the default browser? Are other Sailfish OS applications (e.g. Tweetian) able to open the browser?

Best regards, Sebastian

**Comment by cfabric** [comment]
Hi Sebastian, 

sorry, indeed, my mime-type file was somehow corrupted which prevented the browser to be opened. Fixed, all good now. 

Thanks!
Chris

**Comment by Wunderfitz** [comment]
Glad to read that. Closing this issue then...

Best regards, Sebastian
