### ISSUE TITLE
Feature: Timeline from where I left

### ISSUE THREAD

**Issue by NGC935** [Wunderfitz/harbour-piepmatz#18]
One comment in the Jolla Store mentioned to start from where you read the last messages. I'm also one of these guys, I need to read in the natural flow of time. Thanks in advance and keep up the good work!

**Comment by Wunderfitz** [comment]
Thanks for opening an issue for that. Is certainly on my list for one of the upcoming releases. :)

**Comment by Wunderfitz** [comment]
After a beer I had an idea how to include a preliminary solution to this already in 0.2. As it seems to work surprisingly well, please have a look on the update I released today...

**Comment by Wunderfitz** [comment]
Completely forgot to follow-up. At least for me, the solution which is there since 0.2 works pretty well, so I'm closing this one for now. In case you still have issues, please let me know!
