### ISSUE TITLE
Do not freeze user details in user info

### ISSUE THREAD

**Issue by qeef** [Wunderfitz/harbour-piepmatz#19]
There is a time someone may want to browse some user's posts. However while browsing, user's details covers about half of display, so browsing user's tweets is not so comfort.

**Comment by Wunderfitz** [comment]
Yes, you're absolutely right. I will make the information text on how many tweets the current user currently has clickable. Piepmatz will open a new page where you can see all tweets of this user without any additional stuff on the screen.

**Comment by Wunderfitz** [comment]
This is fixed with 0.3. As outlined above, you have a clickable link which opens a separate page with the tweets of the respective user.
