### ISSUE TITLE
Feature Request: List Support

### ISSUE THREAD

**Issue by adskankster** [Wunderfitz/harbour-piepmatz#27]
Hello, love the application. I mentioned these in the comments, and you asked me to put these on here, so here's the first one. I'll add the other in another request.

List Support: I arrange all the accounts I follow into private lists, so that I can concentrate on specific groups at different times, or if things are busy to keep it managebale. 

It would be great to be able to filter the feed in Piepmatz by List (private or public).

Thanks.

**Comment by Wunderfitz** [comment]
Thanks for the feature request - sounds reasonable. However, may take a while as I'm on a longer summer break. :)

**Comment by adskankster** [comment]
Great, thanks! Whenever's best for you. :)

**Comment by Wunderfitz** [comment]
Took a while... Piepmatz 1.0 with this feature is now released. You can get it from OpenRepos https://openrepos.net/content/werkwolf/piepmatz and from the Jolla Store. Have fun!
