### ISSUE TITLE
Feature Request: View One Account 

### ISSUE THREAD

**Issue by adskankster** [Wunderfitz/harbour-piepmatz#28]
This may be related to https://github.com/Wunderfitz/harbour-piepmatz/issues/23

Some sport accounts provide live updates of matches while they're on. It's great to be able to concentrate on those only. So it would be great to select an account and just get the messages from them - if possible to apply the filter at the twitter server, so less data is used downloading filtered tweets, that would be perfect.

Many thanks.

**Comment by Wunderfitz** [comment]
Mhmm, you can get the tweets of a particular account already now. Just open the profile and press the link to the tweets. However, this might need a "Refresh" option to fulfill your needs. I'll see what I can do. :)

**Comment by adskankster** [comment]
Yes, I found that after I had posted this one, but didn't see a refresh, so left it to see what you came back with. That would be fantastic, thanks!
