### ISSUE TITLE
Possibility to delete tweets

### ISSUE THREAD

**Issue by schmittlauch** [Wunderfitz/harbour-piepmatz#37]
In Piepmatz 0.5 I can't find a possibility to delete my own tweets. Such an option would be quite useful, especially for the countless times I have typos in my tweet.

**Comment by Wunderfitz** [comment]
Yes, that's not yet implemented, but also not that complicated. I consider it for the next release. Until then please check your tweets once again before sending... ;)

**Comment by Wunderfitz** [comment]
Piepmatz 1.0 with this feature is now released. You can get it from OpenRepos https://openrepos.net/content/werkwolf/piepmatz and from the Jolla Store.
