### ISSUE TITLE
Wrong client identification in tweets

### ISSUE THREAD

**Issue by Aslanex** [Wunderfitz/harbour-piepmatz#39]
Tweets sent via Piepmatz are identified as sent by Twitter Lite.

**Comment by Wunderfitz** [comment]
Interesting... However, I have to say that this ID is not set by me, but by Twitter itself, so there's hardly anything I can do. Maybe it was also a temporary issue - your latest tweet seems to be OK again, see screenshot. Can you still reproduce it?

![screenshot_20171127_001](https://user-images.githubusercontent.com/15228698/33270525-a365692e-d384-11e7-9a92-c63dcbeb4da4.png)

**Comment by Aslanex** [comment]
Ok, I can confirm it shows the correct client now, it was probably a temporary bug.
