### ISSUE TITLE
Lack of posibility to remove an account from Piepmatz

### ISSUE THREAD

**Issue by ferlanero** [Wunderfitz/harbour-piepmatz#42]
Since ver. 1.0 is imposible to remove an account from Piepmatz. At the moment we can register 2 accounts but if we want to remove one or even both is imposible.

**Comment by Wunderfitz** [comment]
Yes, simply forgot to implement that. ;) Until I have a solution in place, please proceed as follows: 

- Switch to the account which you want to keep
- Open a file browser and go to /home/nemo/.config/harbour-piepmatz
- Delete all files which have the to-be-deleted account name in their name, probably only two habour-piepmatz-<accountname>.conf and settings-<accountname>.conf
