### ISSUE TITLE
Option to "just retweet"

### ISSUE THREAD

**Issue by yorambh** [Wunderfitz/harbour-piepmatz#46]
a single tweet pully menu gives you the option to "retweet with comment", together with some other options. the most common action, which is just to retweet, without comment, is not exist and can not be achieved by retweet with empty comment.
Unless I'm missing something this seems to be a basic feature that is not exist.

**Comment by Wunderfitz** [comment]
This feature actually exists - it's just not in the pulley menu as I tried to limit the number of options there... Simply press the retweet icon on the tweet itself to retweet and the star icon to favorite/like a tweet. If you have retweeted/favorited a tweet, the symbol and the number will be displayed in highlighted color.
