### ISSUE TITLE
[Feature Request] Multiple account support

### ISSUE THREAD

**Issue by rodneyrod** [Wunderfitz/harbour-piepmatz#5]
Add support for multiple twitter accounts.

**Comment by Wunderfitz** [comment]
Already had that in my mind, but many other things need to come before that. Will keep you updated as soon as I can start with it.

**Comment by AlmuHS** [comment]
I agree with this proposal

**Comment by Wunderfitz** [comment]
Took a while... Piepmatz 1.0 with this feature is now released. You can get it from OpenRepos https://openrepos.net/content/werkwolf/piepmatz and from the Jolla Store.
