### ISSUE TITLE
[Feature] Possibility to mute a thread

### ISSUE THREAD

**Issue by schmittlauch** [Wunderfitz/harbour-piepmatz#53]
Related to #52, the default reply behaviour is to reply to everyone involved in a thread so far, including retweeters.
Although it's possible to edit the receivers of a reply at the sender's side, many people are either not aware of that option or simply don't care. Muting a thread is then a good option to get rid of all these unwanted replies.

This is possible in the twitter web client, but as thread's aren't really exposed in the 3rd party client API I can't say whether implementing this is possible.

**Comment by Wunderfitz** [comment]
As you wrote - no official thread support in 3rd party APIs. The current thread support is also based on a workaround. So unfortunately, I have to close this one. The only thing which might happen in the future might be muting of certain users or keywords...
