### ISSUE TITLE
Twitter new Account API

### ISSUE THREAD

**Issue by marxistvegan** [Wunderfitz/harbour-piepmatz#56]
Not sure if this is necessary to ask, but having seen a number of linux based twitter clients closing shop after Twitter moved to the Account Activity API. Is that something of a concern for piepmatz, though it is still working for me, but just want to know. Thanks!

**Comment by Wunderfitz** [comment]
Sorry for not replying earlier. I haven't seen the issue before... 

Piepmatz was prepared for the API changes from the very beginning. The deprecated account API was never used and the direct messages functionality uses the new API.

Now, all Twitter API changes are in effect - I hope the app still works smoothly for you as it does for me.
