### ISSUE TITLE
My offer to use "Twitter4QML"

### ISSUE THREAD

**Issue by helicalgear** [Wunderfitz/harbour-piepmatz#8]
@Wunderfitz 
Would you please try using Twitter4QML?
I think that you are trying to implement the code to access to TwitterAPI by yourself.
But the Twitter4QML already have implemented the almost of all function to access to the TwitterAPI.
Unfortunately there is not enough document to use it but there are some samples which uses this library.

http://git.qt-users.jp/git/?p=codereview/qneptunea.git;a=tree
http://git.qt-users.jp/git/?p=codereview/sailfishos/qippis.git;a=tree

Of course, there is no problem at all without using it, but I thought that if you use this you thought that you could concentrate on UI implementation, so I suggested it.

Twitter4QML
http://git.qt-users.jp/git/?p=codereview/twitter4qml.git;a=tree

Tnx!!!

**Comment by Wunderfitz** [comment]
Hi! 

Wow, I wasn't aware that your implementation actually exists! Before I started the project I actually searched for something like this, but obviously only used search terms like "Twitter Qt" or similar... Didn't find anything, so I started the implementation on my own. :(

I just had a short look at it and it looks really complete and easy to use. Moreover, the code looks really clean and you even have unit tests - something which I haven't even tried out yet (slightly embarrassing...). You need to know, I'm a C++/Qt beginner (originally an ABAP and Java developer/architect) and consider Piepmatz (also) an opportunity to learn. :) 

The only thing I've noticed is that your code needs to be updated to work with the new extended Tweet format (see https://dev.twitter.com/overview/api/upcoming-changes-to-tweets ), but I'm sure I could do that. 

I'll be on vacation for a little bit more than a week and most certainly will only be able to ship the small bugfix/translation release of Piepmatz before it tomorrow, but afterwards I will certainly work on an integration or at least check how much effort this would be. ;) I guess a major challenge would be to make it work with my oAuth implementation which I would really like to keep... 

So thank you very much already, I'm really excited! 

Best regards, Sebastian

**Comment by helicalgear** [comment]
Hi!

Thank you for your reply.
Twitter4QML was developed by Tasuku Suzuki (https://twitter.com/task_jp) who was a developer of QNeptunea which was one of the most famous twitter client for Nokia N9 (MeeGo).
And (recently it is no so active but) it was continuously maintained by Japan Qt Users Community.
If you interest to use it and/or have some suggestion for this code, we are so happy if you join to developing this library from http://codereview.qt-users.jp/ .

http://codereview.qt-users.jp/#/admin/projects/twitter4qml

There is a instruction: http://qtquick.me/
(Please replace "cr.qtquick.me" to "codereview.qt-users.jp" to read it.)

If you have any question to join it, please do not hesitate to contact me and/or kenya888 (https://github.com/kenya888) who is a main maintainer of infrastructure of qt-users.jp.
And if you have any question for the code itself, please contact Tasuku or me.

Best regards,

**Comment by Wunderfitz** [comment]
Thanks for the detailed information. Will certainly have a look and please send some greetings to the Japanese Qt community! 

Mentioning QNeptunea makes me feel a little nostalgic. Still keeping my N9 like a treasure and thinking what could have been if Nokia made better decisions...

**Comment by Wunderfitz** [comment]
Hi again,

I had a little closer look on Twitter4QML. Though I'm really impressed about its completeness, structuring and style - I'm really afraid that integrating it into Piepmatz would more or less mean a complete rework of many parts of the application. 

Moreover, the extended tweet (and obviously also extended entities) functionality needs to be integrated in addition. As almost every attribute of a Twitter object (e.g. status or user) is explicitly modeled in the respective classes in Twitter4QML, additional fields which come with the recent Twitter extensions would require own attributes, signals/slots and respective testing. Also, the way how Twitter4QML handles the actual tweet text (incl. rich text, links, mentions etc.) is completely different from mine and I would first need to make up my mind which one is better or maybe even get the best of both worlds combined...

This would basically mean that I need to stop integrating additional features in the next weeks (or even months, depending on my free time) and that's certainly something I don't want to do now. I really would like to get image/video attachments and direct messages ready before my summer vacation.

So thanks again for pointing me to this library, but I'll close this issue for now and keep it in mind - at least until I come to a dead end with my current quick (and maybe a little dirty) way of implementing a Twitter API connector...

Best regards, Sebastian
