### ISSUE TITLE
Make active account visible while (re-)tweeting or replying

### ISSUE THREAD

**Issue by DirkMahler** [Wunderfitz/harbour-piepmatz#89]
I'm using Piepmatz with two accounts: a private one and one for an open source project. As both follow a group of same people the visible timelines look very similar. For that reason it happens quite often to me that I'm retweeting or replying from the wrong account.

For that reason it would be very helpful if while performing such actions the currently active account could be visible (e.g. the avatar) or even selectable.

**Comment by Wunderfitz** [comment]
Should be doable, thanks for the idea!

**Comment by Wunderfitz** [comment]
Feature will be in the next version, see commit 126a061.
