### ISSUE TITLE
[Profile] not updated after tweeting

### ISSUE THREAD

**Issue by Nokius** [Wunderfitz/harbour-piepmatz#9]
the stream of Tweets get's not updated when the user tweeted a new tweet. The user needs to do this manually

**Comment by Wunderfitz** [comment]
Accepted for the profile view, that really should be updated after a tweet. However, I won't update the whole timeline after a tweet before I have implemented local caching and with it the ability to keep the current position in the list. :)

**Comment by Nokius** [comment]
This sounds perfect :)
