### ISSUE TITLE
[Error] Piepmatz doesn't shows "show thread" button

### ISSUE THREAD

**Issue by AlmuHS** [Wunderfitz/harbour-piepmatz#91]
Since two days ago, Piepmatz doesn't shows the threads after open a tweet. 
When you open a tweet which includes a thread, the button "show thread" doesn't appears. Even waiting a minutes, the button doesn't appears. 

Could you solve this issue?

**Comment by Wunderfitz** [comment]
Obviously, Twitter modernized their site a few days ago. As a consequence, tweet threads can no longer be extracted directly from the web front-end now. That needs to be done as there is no official API for threads. 

Unfortunately, there is no straight-forward fix, at least I haven't found one yet. But let's see... Any help/hints are appreciated!

**Comment by schmittlauch** [comment]
IBBoard/Cawbird#17 has just renewed their thread handling, if I understand correctly they do it via the Twitter search API. This has the downside of running into the history limits of the API-exposed search (threads can only be linked for a few days after publishing), but is less brittle than doing web scraping.

**Comment by Wunderfitz** [comment]
Yep, also thought about that. But I really don't like consuming the search API for that, it's terribly inefficient and goes against your own API limits... But if there is no other way around it, that would be the solution. I still think it can be done using the NoJS frontend of Twitter, but time is very limited right now as I hardly have any spare time at the moment...
