### ISSUE TITLE
Ampersand gets escaped in URL

### ISSUE THREAD

**Issue by fuchsmich** [Wunderfitz/harbour-piepmatz#98]
EDIT: URLs don't get cut off, but ampersand gets escaped.

----

In [phoronix](https://twitter.com/phoronix)'s tweets URLs are cut off.

In e.g. [this one](https://twitter.com/phoronix/status/1316342527155412992) Piepmatz renders 

> https://www.phoronix.com/scan.php?page=news_item&px=Apache- 

which should be 

> https://www.phoronix.com/scan.php?page=news_item&px=Apache-OpenOffice-20

**Comment by Wunderfitz** [comment]
Can't reproduce the cut off, but for me the link is also rendered incorrectly. The & in the middle is converted to an HTML ampersand '&amp;'...

**Comment by fuchsmich** [comment]
You're right. They're not cut off.
